//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AHKUpdater.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AHKUpdater.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to extraction.
        /// </summary>
        public static string BtnAddForExtractionContent {
            get {
                return ResourceManager.GetString("BtnAddForExtractionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel extraction.
        /// </summary>
        public static string BtnCancelExtractionContent {
            get {
                return ResourceManager.GetString("BtnCancelExtractionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string BtnCancelPathContent {
            get {
                return ResourceManager.GetString("BtnCancelPathContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changeinfo.
        /// </summary>
        public static string BtnChangeSaveContent {
            get {
                return ResourceManager.GetString("BtnChangeSaveContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string BtnDeleteContent {
            get {
                return ResourceManager.GetString("BtnDeleteContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open script.
        /// </summary>
        public static string BtnEditorForOpeningFilesScriptContent {
            get {
                return ResourceManager.GetString("BtnEditorForOpeningFilesScriptContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open XML.
        /// </summary>
        public static string BtnEditorForOpeningFilesXMLContent {
            get {
                return ResourceManager.GetString("BtnEditorForOpeningFilesXMLContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract to script.
        /// </summary>
        public static string BtnExtractToScriptContent {
            get {
                return ResourceManager.GetString("BtnExtractToScriptContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract to XML.
        /// </summary>
        public static string BtnExtractToXmlContent {
            get {
                return ResourceManager.GetString("BtnExtractToXmlContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add parameter.
        /// </summary>
        public static string BtnFunctionAddParameterContent {
            get {
                return ResourceManager.GetString("BtnFunctionAddParameterContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove parameter.
        /// </summary>
        public static string BtnFunctionRemoveParameterToolTip {
            get {
                return ResourceManager.GetString("BtnFunctionRemoveParameterToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save function.
        /// </summary>
        public static string BtnFunctionSaveContent {
            get {
                return ResourceManager.GetString("BtnFunctionSaveContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder.
        /// </summary>
        public static string BtnGetSettingFolder {
            get {
                return ResourceManager.GetString("BtnGetSettingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save hotstring.
        /// </summary>
        public static string BtnHotstringSaveContent {
            get {
                return ResourceManager.GetString("BtnHotstringSaveContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file.
        /// </summary>
        public static string BtnImportFileContent {
            get {
                return ResourceManager.GetString("BtnImportFileContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read file content.
        /// </summary>
        public static string BtnImportReadFile {
            get {
                return ResourceManager.GetString("BtnImportReadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        public static string BtnImportSelectAll {
            get {
                return ResourceManager.GetString("BtnImportSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect all.
        /// </summary>
        public static string BtnImportSelectNone {
            get {
                return ResourceManager.GetString("BtnImportSelectNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from extraction list.
        /// </summary>
        public static string BtnRemoveFromExtractListContent {
            get {
                return ResourceManager.GetString("BtnRemoveFromExtractListContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to file.
        /// </summary>
        public static string BtnSaveContent {
            get {
                return ResourceManager.GetString("BtnSaveContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save settings.
        /// </summary>
        public static string BtnSaveSettingsContent {
            get {
                return ResourceManager.GetString("BtnSaveSettingsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string BtnSelectPathContent {
            get {
                return ResourceManager.GetString("BtnSelectPathContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import file.
        /// </summary>
        public static string BtnStartImport {
            get {
                return ResourceManager.GetString("BtnStartImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save variable.
        /// </summary>
        public static string BtnVariableSaveContent {
            get {
                return ResourceManager.GetString("BtnVariableSaveContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced hotstring.
        /// </summary>
        public static string CbAdvancedHotstringContent {
            get {
                return ResourceManager.GetString("CbAdvancedHotstringContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An advanced hotstring, errorchecking will not be done.
        /// </summary>
        public static string CbAdvancedHotstringToolTip {
            get {
                return ResourceManager.GetString("CbAdvancedHotstringToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include GUI for menu.
        /// </summary>
        public static string CbSaveWithMenuContent {
            get {
                return ResourceManager.GetString("CbSaveWithMenuContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code for function here.
        /// </summary>
        public static string CodeNewFunctionInfo {
            get {
                return ResourceManager.GetString("CodeNewFunctionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewParameter.
        /// </summary>
        public static string CodeNewParameter {
            get {
                return ResourceManager.GetString("CodeNewParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import old data.
        /// </summary>
        public static string ExpImportHeader {
            get {
                return ResourceManager.GetString("ExpImportHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string ExpParametersHeader {
            get {
                return ResourceManager.GetString("ExpParametersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application-settings.
        /// </summary>
        public static string GrpBoxApplicationSettingsHeader {
            get {
                return ResourceManager.GetString("GrpBoxApplicationSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functional settings.
        /// </summary>
        public static string GrpBoxFunctionSettingsHeader {
            get {
                return ResourceManager.GetString("GrpBoxFunctionSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scriptoperations.
        /// </summary>
        public static string GrpBoxFunctionSettingsScriptOperationsHeader {
            get {
                return ResourceManager.GetString("GrpBoxFunctionSettingsScriptOperationsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script settings.
        /// </summary>
        public static string GrpBoxScriptSettingsHeader {
            get {
                return ResourceManager.GetString("GrpBoxScriptSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section texts.
        /// </summary>
        public static string GrpBoxSectionTextsHeader {
            get {
                return ResourceManager.GetString("GrpBoxSectionTextsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A hotstring is currently being edited, do you which to save this?.
        /// </summary>
        public static string HotstringVerifySaveUnsavedEdit {
            get {
                return ResourceManager.GetString("HotstringVerifySaveUnsavedEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new hotstring is currently being created, do you which to save this?.
        /// </summary>
        public static string HotstringVerifySaveUnsavedEditNew {
            get {
                return ResourceManager.GetString("HotstringVerifySaveUnsavedEditNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu trigger.
        /// </summary>
        public static string LblAhkMenuTriggerTitleContent {
            get {
                return ResourceManager.GetString("LblAhkMenuTriggerTitleContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change date.
        /// </summary>
        public static string LblChangeNameTitleContent {
            get {
                return ResourceManager.GetString("LblChangeNameTitleContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select editor to open files with.
        /// </summary>
        public static string LblEditorForOpeningFilesContent {
            get {
                return ResourceManager.GetString("LblEditorForOpeningFilesContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function name.
        /// </summary>
        public static string LblFunctionNameTitleContent {
            get {
                return ResourceManager.GetString("LblFunctionNameTitleContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functions.
        /// </summary>
        public static string LblFunctionsToImportTitle {
            get {
                return ResourceManager.GetString("LblFunctionsToImportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu title.
        /// </summary>
        public static string LblHotstringMenuItemTitleContent {
            get {
                return ResourceManager.GetString("LblHotstringMenuItemTitleContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotstring name.
        /// </summary>
        public static string LblHotstringNameTitleContent {
            get {
                return ResourceManager.GetString("LblHotstringNameTitleContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hostrings.
        /// </summary>
        public static string LblHotstringsToImportTitle {
            get {
                return ResourceManager.GetString("LblHotstringsToImportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string LblHotstringSystemTitleContent {
            get {
                return ResourceManager.GetString("LblHotstringSystemTitleContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File to import.
        /// </summary>
        public static string LblImportFileContent {
            get {
                return ResourceManager.GetString("LblImportFileContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title for functions-section.
        /// </summary>
        public static string LblSectionTextFunctionsTitleTitleContent {
            get {
                return ResourceManager.GetString("LblSectionTextFunctionsTitleTitleContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title for hotstrings-section.
        /// </summary>
        public static string LblSectionTextHotstringsTitleTitleContent {
            get {
                return ResourceManager.GetString("LblSectionTextHotstringsTitleTitleContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title for menutriggers-section.
        /// </summary>
        public static string LblSectionTextMenuActionTriggersTitleTitleContent {
            get {
                return ResourceManager.GetString("LblSectionTextMenuActionTriggersTitleTitleContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title for menu-section.
        /// </summary>
        public static string LblSectionTextMenuTitleTitleContent {
            get {
                return ResourceManager.GetString("LblSectionTextMenuTitleTitleContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titledivider-character.
        /// </summary>
        public static string LblSectionTextTitleDeviderTitleTitleContent {
            get {
                return ResourceManager.GetString("LblSectionTextTitleDeviderTitleTitleContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title for variables-section.
        /// </summary>
        public static string LblSectionTextVariablesTitleTitleContent {
            get {
                return ResourceManager.GetString("LblSectionTextVariablesTitleTitleContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable name.
        /// </summary>
        public static string LblVariableNameTitleContent {
            get {
                return ResourceManager.GetString("LblVariableNameTitleContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables.
        /// </summary>
        public static string LblVariablesToImportTitle {
            get {
                return ResourceManager.GetString("LblVariablesToImportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string LblVariableValueTitleContent {
            get {
                return ResourceManager.GetString("LblVariableValueTitleContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items to extract.
        /// </summary>
        public static string LvExtractListTitleContent {
            get {
                return ResourceManager.GetString("LvExtractListTitleContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New command.
        /// </summary>
        public static string MainMenuNewCommand {
            get {
                return ResourceManager.GetString("MainMenuNewCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function.
        /// </summary>
        public static string MainMenuNewFunction {
            get {
                return ResourceManager.GetString("MainMenuNewFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotstring.
        /// </summary>
        public static string MainMenuNewHotstring {
            get {
                return ResourceManager.GetString("MainMenuNewHotstring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable.
        /// </summary>
        public static string MainMenuNewVariable {
            get {
                return ResourceManager.GetString("MainMenuNewVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new culture will be used at next startup.
        /// </summary>
        public static string MsgCultureChanged {
            get {
                return ResourceManager.GetString("MsgCultureChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when reading file. Will start with empty content.
        /// </summary>
        public static string MsgErrorReadingFile {
            get {
                return ResourceManager.GetString("MsgErrorReadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string MsgErrorReadingFileButton {
            get {
                return ResourceManager.GetString("MsgErrorReadingFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected objects extracted to:.
        /// </summary>
        public static string MsgExtractedTo {
            get {
                return ResourceManager.GetString("MsgExtractedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to functions.
        /// </summary>
        public static string MsgImportedFunctions {
            get {
                return ResourceManager.GetString("MsgImportedFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hotstrings.
        /// </summary>
        public static string MsgImportedHotstrings {
            get {
                return ResourceManager.GetString("MsgImportedHotstrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to variables.
        /// </summary>
        public static string MsgImportedVariables {
            get {
                return ResourceManager.GetString("MsgImportedVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find any XML-file to read content. Will start with empty content..
        /// </summary>
        public static string MsgNoXmlFileFound {
            get {
                return ResourceManager.GetString("MsgNoXmlFileFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items were imported.
        /// </summary>
        public static string MsgNumImported {
            get {
                return ResourceManager.GetString("MsgNumImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unsaved changes. Do you want to save these before closing the application?.
        /// </summary>
        public static string MsgQSaveBeforeClosing {
            get {
                return ResourceManager.GetString("MsgQSaveBeforeClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save (script without GUI).
        /// </summary>
        public static string MsgQSaveBeforeClosingBtn1 {
            get {
                return ResourceManager.GetString("MsgQSaveBeforeClosingBtn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save (script with GUI).
        /// </summary>
        public static string MsgQSaveBeforeClosingBtn2 {
            get {
                return ResourceManager.GetString("MsgQSaveBeforeClosingBtn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string MsgQSaveBeforeClosingBtn3 {
            get {
                return ResourceManager.GetString("MsgQSaveBeforeClosingBtn3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved changes.
        /// </summary>
        public static string MsgQSaveBeforeClosingTitle {
            get {
                return ResourceManager.GetString("MsgQSaveBeforeClosingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data have been changed, but is not saved. Do you want to save before closing the application?.
        /// </summary>
        public static string MsgSaveBeforeClosing {
            get {
                return ResourceManager.GetString("MsgSaveBeforeClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created at.
        /// </summary>
        public static string ScriptFileCreatedAt {
            get {
                return ResourceManager.GetString("ScriptFileCreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to default.
        /// </summary>
        public static string SettingsResetValueButtonContent {
            get {
                return ResourceManager.GetString("SettingsResetValueButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes.
        /// </summary>
        public static string SuggestedPathAttributesHeader {
            get {
                return ResourceManager.GetString("SuggestedPathAttributesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string SuggestedPathHeader {
            get {
                return ResourceManager.GetString("SuggestedPathHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog.
        /// </summary>
        public static string TiChangelogHeader {
            get {
                return ResourceManager.GetString("TiChangelogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functions.
        /// </summary>
        public static string TiFunctionsHeader {
            get {
                return ResourceManager.GetString("TiFunctionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotstrings.
        /// </summary>
        public static string TiHotstringsHeader {
            get {
                return ResourceManager.GetString("TiHotstringsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables.
        /// </summary>
        public static string TiHVariablesHeader {
            get {
                return ResourceManager.GetString("TiHVariablesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string TiSettingsHeader {
            get {
                return ResourceManager.GetString("TiSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To extract.
        /// </summary>
        public static string TiToExtractHeader {
            get {
                return ResourceManager.GetString("TiToExtractHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code must contain something.
        /// </summary>
        public static string ValidationErrorFunctionCodeEmpty {
            get {
                return ResourceManager.GetString("ValidationErrorFunctionCodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is already in use.
        /// </summary>
        public static string ValidationErrorFunctionNameAlreadyInUse {
            get {
                return ResourceManager.GetString("ValidationErrorFunctionNameAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name can not contain any whitespace character.
        /// </summary>
        public static string ValidationErrorFunctionNameContainsWhiteSpace {
            get {
                return ResourceManager.GetString("ValidationErrorFunctionNameContainsWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name can not be empty.
        /// </summary>
        public static string ValidationErrorFunctionNameEmpty {
            get {
                return ResourceManager.GetString("ValidationErrorFunctionNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code must contain something.
        /// </summary>
        public static string ValidationErrorHotstringCodeEmpty {
            get {
                return ResourceManager.GetString("ValidationErrorHotstringCodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code will not post text.
        /// </summary>
        public static string ValidationErrorHotstringCodeNoParenthesis {
            get {
                return ResourceManager.GetString("ValidationErrorHotstringCodeNoParenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is already in use.
        /// </summary>
        public static string ValidationErrorHotstringNameAlreadyInUse {
            get {
                return ResourceManager.GetString("ValidationErrorHotstringNameAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name can not contain any whitespace character.
        /// </summary>
        public static string ValidationErrorHotstringNameContainsWhiteSpace {
            get {
                return ResourceManager.GetString("ValidationErrorHotstringNameContainsWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name can not be empty.
        /// </summary>
        public static string ValidationErrorHotstringNameEmpty {
            get {
                return ResourceManager.GetString("ValidationErrorHotstringNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Systemname can not contain any whitespace character.
        /// </summary>
        public static string ValidationErrorHotstringSystemContainsWhiteSpace {
            get {
                return ResourceManager.GetString("ValidationErrorHotstringSystemContainsWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System can not be empty.
        /// </summary>
        public static string ValidationErrorHotstringSystemEmpty {
            get {
                return ResourceManager.GetString("ValidationErrorHotstringSystemEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is already in use as a function.
        /// </summary>
        public static string ValidationErrorNameAlreadyInUseAsFunction {
            get {
                return ResourceManager.GetString("ValidationErrorNameAlreadyInUseAsFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is already in use as a hotstring.
        /// </summary>
        public static string ValidationErrorNameAlreadyInUseAsHotstring {
            get {
                return ResourceManager.GetString("ValidationErrorNameAlreadyInUseAsHotstring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is already in use as a setting.
        /// </summary>
        public static string ValidationErrorNameAlreadyInUseAsSetting {
            get {
                return ResourceManager.GetString("ValidationErrorNameAlreadyInUseAsSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is already in use as a variable.
        /// </summary>
        public static string ValidationErrorNameAlreadyInUseAsVariable {
            get {
                return ResourceManager.GetString("ValidationErrorNameAlreadyInUseAsVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of parameter already exists in this function.
        /// </summary>
        public static string ValidationErrorParameterNameAlreadyInUse {
            get {
                return ResourceManager.GetString("ValidationErrorParameterNameAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory does not exist.
        /// </summary>
        public static string ValidationErrorSettingDirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("ValidationErrorSettingDirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not one of available valid values.
        /// </summary>
        public static string ValidationErrorSettingNotOneOfAvailableValues {
            get {
                return ResourceManager.GetString("ValidationErrorSettingNotOneOfAvailableValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must have a value set.
        /// </summary>
        public static string ValidationErrorSettingValueEmpty {
            get {
                return ResourceManager.GetString("ValidationErrorSettingValueEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is already in use.
        /// </summary>
        public static string ValidationErrorVariableNameAlreadyInUse {
            get {
                return ResourceManager.GetString("ValidationErrorVariableNameAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name can not contain any whitespace character.
        /// </summary>
        public static string ValidationErrorVariableNameContainsWhiteSpace {
            get {
                return ResourceManager.GetString("ValidationErrorVariableNameContainsWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name can not be empty.
        /// </summary>
        public static string ValidationErrorVariableNameEmpty {
            get {
                return ResourceManager.GetString("ValidationErrorVariableNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The culture specified in the save-file is not valid. Default value of &apos;en&apos; (english) will be used..
        /// </summary>
        public static string ValidationInvalidCulture {
            get {
                return ResourceManager.GetString("ValidationInvalidCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string located in the save-file is: .
        /// </summary>
        public static string ValidationInvalidCultureInfoUsed {
            get {
                return ResourceManager.GetString("ValidationInvalidCultureInfoUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No culture have been specified in the save-file. Default value of &apos;en&apos; (english) will be used..
        /// </summary>
        public static string ValidationNoCultureSpecified {
            get {
                return ResourceManager.GetString("ValidationNoCultureSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code should contain something.
        /// </summary>
        public static string ValidationWarningFunctionCodeEmpty {
            get {
                return ResourceManager.GetString("ValidationWarningFunctionCodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If menutitle is left empty, a default string will be used.
        /// </summary>
        public static string ValidationWarningHotstringMenuTitleEmpty {
            get {
                return ResourceManager.GetString("ValidationWarningHotstringMenuTitleEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value should be set to something.
        /// </summary>
        public static string ValidationWarningVariableValueEmpty {
            get {
                return ResourceManager.GetString("ValidationWarningVariableValueEmpty", resourceCulture);
            }
        }
    }
}
